import { createFileRoute } from "@tanstack/react-router";
import { SiteNav, Disclaimer } from "@/components/site-nav";

export const Route = createFileRoute("/sources")({
  head: () => ({
    meta: [
      { title: "Data Sources — Global Equity Terminal v2" },
      { name: "description", content: "Free and public data sources powering price, fundamentals, and corporate events in Global Equity Terminal v2." },
      { property: "og:title", content: "Data Sources — Global Equity Terminal v2" },
      { property: "og:description", content: "Free and public data sources powering price, fundamentals, and corporate events in Global Equity Terminal v2." },
    ],
    links: [{ rel: "canonical", href: "https://rankaisolutions.tech/sources" }],
  }),
  component: SourcesPage,
});

const SOURCES = [
  {
    name: "Finimpulse API",
    role: "Primary provider",
    metrics: ["Quote / price", "Trailing P/E", "Market cap (local + USD)", "Avg volume", "52W high / low", "MA50 / MA200", "Sector / industry", "Earnings date"],
    freshness: "Delayed (15–20 min) on most exchanges",
    reliability: "High",
    notes: "Used as the canonical metadata + summary source. Falls back to mock when unavailable.",
    rights: "Data displayed under Finimpulse's terms of service. All market data remains the property of the originating exchanges and Finimpulse.",
    url: "https://api.finimpulse.com/",
  },
  {
    name: "Perplexity (News)",
    role: "News & catalysts",
    metrics: ["AI-summarized news", "Citations to source articles"],
    freshness: "Live web search",
    reliability: "Medium — AI-summarized; verify with cited sources",
    notes: "Powers the News & Catalysts panel. We never store or redistribute headlines or article text — only the AI-generated paraphrase plus links back to original publishers.",
    rights: "Cited articles remain the property of their original publishers. Click citations to read at the source.",
    url: "https://www.perplexity.ai/",
  },
  {
    name: "Lovable AI Gateway",
    role: "Narrative generation",
    metrics: ["AI thesis grounded in on-page metrics"],
    freshness: "On-demand",
    reliability: "Medium — AI-generated commentary",
    notes: "Used by the AI Narrative panel. The model only sees metrics computed by the terminal — no external news or forecasts are fed in.",
    rights: "AI output is generated from your in-app metrics. Not a verified statement of fact.",
  },
  {
    name: "Curated Universe",
    role: "Discovery seed",
    metrics: ["Ticker", "Exchange", "Region", "Country", "Currency", "Sector", "Industry"],
    freshness: "Static — curated list",
    reliability: "High",
    notes: "~150 hand-picked liquid global names across US, India, EU, JP, HK, KR, TW, AU, SG.",
    rights: "Ticker symbols and company names are factual identifiers used for reference. Trademarks belong to their respective owners.",
  },
  {
    name: "Mock demo provider",
    role: "Fallback only",
    metrics: ["All metrics deterministically derived from ticker hash"],
    freshness: "Mock",
    reliability: "Demo / not live",
    notes: "Activated per-row when upstream sources fail. Always badged as 'mock' in the UI.",
    rights: "Synthetic data generated by the terminal — no third-party rights apply.",
  },
] as const;

function SourcesPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <SiteNav />
      <main className="flex-1 max-w-[1400px] mx-auto px-4 py-6 w-full">
        <h1 className="text-xl font-semibold tracking-tight">Data Sources</h1>
        <p className="text-xs text-muted-foreground mt-1 max-w-3xl">
          The terminal blends free / public sources with deterministic mock fallback for resilience. We never silently mix mock and real data — when mock is used,
          rows are badged accordingly and confidence is reduced.
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-4">
          {SOURCES.map((s) => (
            <div key={s.name} className="panel p-4">
              <div className="flex items-baseline justify-between flex-wrap gap-2">
                <div className="font-mono text-primary text-sm">{s.name}</div>
                <span className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground border border-border rounded px-2 py-0.5">{s.role}</span>
              </div>
              <div className="mt-3 grid grid-cols-2 gap-x-4 gap-y-1 text-xs">
                <div className="text-muted-foreground">Freshness</div><div>{s.freshness}</div>
                <div className="text-muted-foreground">Reliability</div><div>{s.reliability}</div>
              </div>
              <div className="mt-3">
                <div className="text-[10px] font-mono uppercase tracking-widest text-muted-foreground">Provides</div>
                <div className="mt-1 flex flex-wrap gap-1">
                  {s.metrics.map((m) => (
                    <span key={m} className="text-[10px] font-mono border border-border rounded px-1.5 py-0.5 text-muted-foreground">{m}</span>
                  ))}
                </div>
              </div>
              <p className="mt-3 text-xs text-muted-foreground leading-relaxed">{s.notes}</p>
              {"url" in s && s.url && (
                <a href={s.url} target="_blank" rel="noreferrer" className="mt-3 inline-block text-[10px] font-mono text-primary hover:underline">
                  {s.url} ↗
                </a>
              )}
            </div>
          ))}
        </div>

        <div className="panel mt-6 p-5 text-xs text-muted-foreground leading-relaxed">
          <div className="font-mono text-primary uppercase tracking-widest mb-2">Source priority (PRD)</div>
          <ol className="list-decimal pl-5 space-y-1">
            <li>Official exchange data</li>
            <li>Company investor relations</li>
            <li>Recognized financial data providers (Finimpulse)</li>
            <li>Major finance websites</li>
            <li>Public knowledge sources for basic metadata</li>
          </ol>
        </div>

        <Disclaimer />
      </main>
    </div>
  );
}
