import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Preview,
  Section,
  Text,
} from '@react-email/components'
import type { TemplateEntry } from './registry'

const SITE_NAME = 'Global Equity Terminal'

interface MorningBriefProps {
  date?: string
  symbols?: string[]
  summary?: string
  highlights?: Array<{ symbol: string; perf5d?: number | null; rsi14?: number | null }>
}

const MorningBriefEmail = ({
  date,
  symbols = [],
  summary = '',
  highlights = [],
}: MorningBriefProps) => {
  const headline = date ? `Morning Brief — ${date}` : 'Morning Brief'
  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>{summary.slice(0, 110)}</Preview>
      <Body style={main}>
        <Container style={container}>
          <Text style={brandTag}>{SITE_NAME}</Text>
          <Heading style={h1}>{headline}</Heading>
          <Text style={meta}>
            {symbols.length} ticker{symbols.length === 1 ? '' : 's'} ·{' '}
            {symbols.slice(0, 8).join(' · ')}
            {symbols.length > 8 ? ' …' : ''}
          </Text>
          <Hr style={hr} />
          <Section>
            <Text style={text}>{summary}</Text>
          </Section>
          {highlights.length > 0 ? (
            <>
              <Hr style={hr} />
              <Heading as="h2" style={h2}>
                Notable moves
              </Heading>
              {highlights.map((h) => (
                <Text key={h.symbol} style={hiRow}>
                  <span style={hiSym}>{h.symbol}</span>
                  <span style={hiVal}>
                    {typeof h.perf5d === 'number'
                      ? `${h.perf5d > 0 ? '+' : ''}${h.perf5d.toFixed(2)}% 5D`
                      : '—'}
                    {typeof h.rsi14 === 'number' ? ` · RSI ${h.rsi14.toFixed(0)}` : ''}
                  </span>
                </Text>
              ))}
            </>
          ) : null}
          <Hr style={hr} />
          <Text style={footer}>
            Generated by {SITE_NAME}. Research only — not investment advice.
          </Text>
        </Container>
      </Body>
    </Html>
  )
}

export const template = {
  component: MorningBriefEmail,
  subject: (data: Record<string, any>) =>
    data?.date ? `Morning Brief — ${data.date}` : 'Your Morning Brief',
  displayName: 'Morning Brief',
  previewData: {
    date: '2026-05-01',
    symbols: ['AAPL', 'MSFT', 'NVDA', 'ASML', 'TSM'],
    summary:
      'Mega-cap tech firm; NVDA leads with a 4.2% 5D move while ASML cools after a strong week. RSI signals are mostly neutral. EU semis look stretched short-term. Not investment advice.',
    highlights: [
      { symbol: 'NVDA', perf5d: 4.2, rsi14: 64 },
      { symbol: 'ASML', perf5d: -2.6, rsi14: 48 },
      { symbol: 'TSM', perf5d: 1.9, rsi14: 56 },
    ],
  },
} satisfies TemplateEntry

const main = { backgroundColor: '#ffffff', fontFamily: 'Inter, Arial, sans-serif' }
const brandTag = {
  fontFamily: 'JetBrains Mono, monospace',
  fontSize: '11px',
  letterSpacing: '0.12em',
  textTransform: 'uppercase' as const,
  color: '#b45309',
  margin: '0 0 14px',
}
const container = { padding: '24px', maxWidth: '560px' }
const h1 = { fontSize: '22px', fontWeight: 700, color: '#0f172a', margin: '0 0 4px' }
const h2 = { fontSize: '14px', fontWeight: 600, color: '#0f172a', margin: '8px 0' }
const meta = { fontSize: '12px', color: '#64748b', margin: '0 0 12px', fontFamily: 'JetBrains Mono, monospace' }
const text = { fontSize: '14px', color: '#1e293b', lineHeight: '1.6', margin: '0' }
const hr = { borderColor: '#e2e8f0', margin: '20px 0' }
const hiRow = { fontSize: '13px', color: '#0f172a', margin: '4px 0', display: 'flex', justifyContent: 'space-between' as const }
const hiSym = { fontFamily: 'JetBrains Mono, monospace', fontWeight: 600 }
const hiVal = { fontFamily: 'JetBrains Mono, monospace', color: '#475569' }
const footer = { fontSize: '11px', color: '#94a3b8', margin: '0' }
